### ISSUE TITLE
Issue executing  "make chaincode"

### ISSUE THREAD

**Issue by sagarduwal** [PacktPublishing/Handson-Blockchain-Development-with-Hyperledger#1]
src/github.com/trade_workflow/accessControlUtils.go:22:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/go/src/github.com/trade_workflow/vendor/github.com/golang/protobuf/proto (vendor tree)
	/usr/local/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/go/src/github.com/golang/protobuf/proto (from $GOPATH)
src/github.com/trade_workflow/keyUtils.go:20:2: cannot find package "github.com/hyperledger/fabric/core/chaincode/shim" in any of:
	/go/src/github.com/trade_workflow/vendor/github.com/hyperledger/fabric/core/chaincode/shim (vendor tree)
	/usr/local/go/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOROOT)
	/go/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOPATH)
src/github.com/trade_workflow/accessControlUtils.go:23:2: cannot find package "github.com/hyperledger/fabric/protos/msp" in any of:
	/go/src/github.com/trade_workflow/vendor/github.com/hyperledger/fabric/protos/msp (vendor tree)
	/usr/local/go/src/github.com/hyperledger/fabric/protos/msp (from $GOROOT)
	/go/src/github.com/hyperledger/fabric/protos/msp (from $GOPATH)
src/github.com/trade_workflow/tradeWorkflow.go:27:2: cannot find package "github.com/hyperledger/fabric/protos/peer" in any of:
	/go/src/github.com/trade_workflow/vendor/github.com/hyperledger/fabric/protos/peer (vendor tree)
	/usr/local/go/src/github.com/hyperledger/fabric/protos/peer (from $GOROOT)
	/go/src/github.com/hyperledger/fabric/protos/peer (from $GOPATH)
cp: cannot stat '/go/src/trade_workflow': No such file or directory
Makefile:32: recipe for target 'chaincode' failed
make: *** [chaincode] Error 1

**Comment by Karimai** [comment]
This might be helpful: 
go get -u github.com/golang/protobuf/proto
